import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { computeRequirementProgress } from "@/lib/medicaid-requirements";

function escapeHtml(s: string) {
  return String(s ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

async function sendResend(to: string[], subject: string, html: string) {
  const key = process.env.RESEND_API_KEY;
  if (!key || to.length === 0) return;
  try {
    await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
      body: JSON.stringify({
        from: "Medicaid Success <onboarding@resend.dev>",
        to, subject, html,
      }),
    });
  } catch (err) {
    console.error("Resend send failed", err);
  }
}

function buildEmailHtml(opts: {
  heading: string; intro: string; verdict: string; report: string;
  missing: string[]; satisfied: string[]; portalUrl: string;
}) {
  const NAVY = "#0b3d91";
  const list = (items: string[], done: boolean) => items.length === 0 ? "" :
    `<ul style="margin:6px 0 14px 20px;padding:0;color:#0f172a;font-size:14px;line-height:1.6">
      ${items.map(i => `<li>${done ? "✅ " : "⚠️ "}${escapeHtml(i)}</li>`).join("")}
    </ul>`;
  return `<!doctype html><html><body style="margin:0;background:#f4f7fc;font-family:Arial,sans-serif;color:#0f172a">
    <div style="max-width:620px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #e2e8f0">
      <div style="background:${NAVY};color:#fff;padding:22px 28px">
        <div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;opacity:.85">Medicaid Success</div>
        <div style="font-size:20px;font-weight:700;margin-top:4px">${escapeHtml(opts.heading)}</div>
      </div>
      <div style="padding:26px 28px;font-size:15px;line-height:1.6">
        <p style="margin:0 0 12px">${escapeHtml(opts.intro)}</p>
        <div style="background:#f1f5fb;border:1px solid #e2e8f0;border-radius:8px;padding:14px 16px;margin:14px 0">
          <div style="font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:#64748b">AI Verdict</div>
          <div style="font-size:17px;font-weight:700;color:${NAVY};margin-top:4px">${escapeHtml(opts.verdict)}</div>
        </div>
        ${opts.missing.length ? `<p style="margin:16px 0 4px;font-weight:600;color:${NAVY}">Still missing — please upload:</p>${list(opts.missing, false)}` : ""}
        ${opts.satisfied.length ? `<p style="margin:8px 0 4px;font-weight:600;color:#166534">Received:</p>${list(opts.satisfied, true)}` : ""}
        <div style="margin:18px 0 6px;font-weight:600;color:${NAVY}">Screening report</div>
        <div style="white-space:pre-wrap;font-size:14px;color:#0f172a;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px">${escapeHtml(opts.report)}</div>
        <div style="margin:22px 0 6px">
          <a href="${opts.portalUrl}" style="display:inline-block;background:${NAVY};color:#fff;text-decoration:none;padding:12px 22px;border-radius:8px;font-weight:600">Open my portal</a>
        </div>
        <p style="margin:18px 0 0;color:#64748b;font-size:13px">This is an automated screening estimate. Your specialist will confirm the final eligibility decision.</p>
      </div>
    </div></body></html>`;
}

type Part =
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: { url: string } }
  | { type: "file"; file: { filename: string; file_data: string } };

// Analyze every document the user uploaded and return a plain-language
// Medicaid eligibility assessment generated by Lovable AI.
export const analyzeEligibility = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { supabase, userId } = context;
    const key = process.env.LOVABLE_API_KEY;
    if (!key) throw new Error("AI service is not configured.");

    const { data: docs, error: listErr } = await supabase
      .from("documents")
      .select("id, name, storage_path, mime_type, size_bytes")
      .eq("user_id", userId)
      .order("created_at", { ascending: true })
      .limit(25);
    if (listErr) { console.error("[db]", listErr.message); throw new Error("Operation failed. Please try again."); }
    if (!docs || docs.length === 0) {
      throw new Error("Upload at least one document before running the analysis.");
    }

    const MAX_BYTES = 6 * 1024 * 1024; // per file, sent to the model
    const parts: Part[] = [
      {
        type: "text",
        text:
          "You are a Medicaid eligibility screener. Review every attached document for a Long-Term Care Medicaid application. " +
          "Return a clear, plain-language report with these sections:\n\n" +
          "1. **Eligibility verdict** — one of: ✅ Likely Eligible, ⚠️ More Information Needed, or ❌ Likely Ineligible.\n" +
          "2. **Why** — 2-4 short bullets explaining the verdict based on income, assets, identity, and citizenship signals you actually saw in the documents.\n" +
          "3. **Documents reviewed** — bullet list naming each file and what it appeared to be.\n" +
          "4. **Missing or unclear items** — concrete next steps the applicant should take.\n\n" +
          "Be cautious: this is a screening estimate, not a legal determination. End with one sentence reminding the user that their specialist will confirm the final decision.",
      },
    ];

    const reviewed: { name: string; status: string }[] = [];

    for (const d of docs) {
      if ((d.size_bytes ?? 0) > MAX_BYTES) {
        reviewed.push({ name: d.name, status: "skipped (too large)" });
        continue;
      }
      const { data: blob, error: dlErr } = await supabase.storage
        .from("documents")
        .download(d.storage_path);
      if (dlErr || !blob) {
        reviewed.push({ name: d.name, status: "skipped (download failed)" });
        continue;
      }
      const bytes = new Uint8Array(await blob.arrayBuffer());
      const b64 = Buffer.from(bytes).toString("base64");
      const mime = (d.mime_type ?? "").toLowerCase();
      const lower = d.name.toLowerCase();

      if (mime.startsWith("image/") || /\.(png|jpe?g|webp|gif)$/i.test(lower)) {
        const ct = mime.startsWith("image/") ? mime : "image/jpeg";
        parts.push({ type: "image_url", image_url: { url: `data:${ct};base64,${b64}` } });
        reviewed.push({ name: d.name, status: "sent (image)" });
      } else if (mime.includes("pdf") || lower.endsWith(".pdf")) {
        parts.push({
          type: "file",
          file: { filename: d.name, file_data: `data:application/pdf;base64,${b64}` },
        });
        reviewed.push({ name: d.name, status: "sent (pdf)" });
      } else {
        reviewed.push({ name: d.name, status: "skipped (unsupported type)" });
      }
    }

    const body = {
      model: "google/gemini-2.5-flash",
      messages: [
        {
          role: "system",
          content:
            "You are a careful Medicaid eligibility screener. Only use information visible in the attached documents. Never invent numbers.",
        },
        { role: "user", content: parts },
      ],
    };

    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Lovable-API-Key": key,
      },
      body: JSON.stringify(body),
    });

    if (!res.ok) {
      const errText = await res.text().catch(() => "");
      if (res.status === 429) throw new Error("The AI is busy. Please try again in a moment.");
      if (res.status === 402) throw new Error("AI credits are exhausted. Please contact the site administrator.");
      throw new Error(`Eligibility analysis failed (${res.status}). ${errText.slice(0, 200)}`);
    }

    const json = (await res.json()) as {
      choices?: { message?: { content?: string } }[];
    };
    const reply = json.choices?.[0]?.message?.content?.trim() ?? "";
    if (!reply) throw new Error("The AI returned an empty response. Please try again.");

    let verdict: "eligible" | "needs_info" | "ineligible" = "needs_info";
    const low = reply.toLowerCase();
    if (low.includes("likely eligible") || low.includes("✅")) verdict = "eligible";
    else if (low.includes("likely ineligible") || low.includes("❌")) verdict = "ineligible";

    await supabase.from("check_ins").insert({
      user_id: userId,
      title: "AI eligibility screening completed",
      body: reply.slice(0, 1000),
      status: verdict === "eligible" ? "success" : verdict === "ineligible" ? "warning" : "info",
    });

    // Fire-and-forget email notifications to the user and all admins.
    try {
      const { data: authUser } = await supabase.auth.getUser();
      const userEmail = authUser?.user?.email ?? null;
      const { data: profile } = await supabase.from("profiles").select("full_name").eq("id", userId).maybeSingle();
      const displayName = profile?.full_name?.trim() || userEmail || "Applicant";

      const filenames = docs.map((d) => d.name);
      const progress = computeRequirementProgress(filenames);

      const verdictLabel =
        verdict === "eligible" ? "✅ Likely Eligible — application ready"
          : verdict === "ineligible" ? "❌ Likely Ineligible — needs review"
          : "⚠️ More Information Needed";

      const portalUrl = "https://medicaid-sucess-onboarding.lovable.app/portal";
      const complete = verdict === "eligible" && progress.missing.length === 0;

      // --- User email ---
      if (userEmail) {
        const heading = complete
          ? "Your application is complete"
          : "Action needed — your application isn't finished yet";
        const intro = complete
          ? `Hi ${displayName.split(" ")[0]}, great news — our AI screening reviewed your uploads and everything looks in order. Your specialist will take it from here.`
          : `Hi ${displayName.split(" ")[0]}, we ran an AI screening on your uploaded documents. Your application is not complete yet — please upload the missing items below so we can move forward.`;
        await sendResend(
          [userEmail],
          complete
            ? "✅ Your Medicaid application is complete"
            : "Reminder: your Medicaid application is missing documents",
          buildEmailHtml({
            heading, intro, verdict: verdictLabel, report: reply,
            missing: progress.missing, satisfied: progress.satisfiedLabels, portalUrl,
          }),
        );
      }

      // --- Admin email(s) ---
      try {
        const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
        const { data: adminRoles } = await supabaseAdmin
          .from("user_roles").select("user_id").eq("role", "admin").eq("status", "approved");
        const adminEmails: string[] = [];
        for (const r of adminRoles ?? []) {
          const { data: u } = await supabaseAdmin.auth.admin.getUserById(r.user_id);
          if (u?.user?.email) adminEmails.push(u.user.email);
        }
        if (adminEmails.length) {
          await sendResend(
            adminEmails,
            `[Medicaid Success] ${verdictLabel} — ${displayName}`,
            buildEmailHtml({
              heading: complete ? "Client application complete" : "Client application incomplete",
              intro: `${displayName} (${userEmail ?? "no email"}) just ran an AI eligibility screening. ${complete ? "All required documents are on file." : "The applicant is still missing required documents."}`,
              verdict: verdictLabel, report: reply,
              missing: progress.missing, satisfied: progress.satisfiedLabels,
              portalUrl: "https://medicaid-sucess-onboarding.lovable.app/crm",
            }),
          );
        }
      } catch (err) {
        console.error("Admin notify failed", err);
      }
    } catch (err) {
      console.error("Eligibility notification failed", err);
    }

    return { report: reply, verdict, reviewed, totalDocs: docs.length };
  });