import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

type Part =
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: { url: string } }
  | { type: "file"; file: { filename: string; file_data: string } };

// Analyze every document the user uploaded and return a plain-language
// Medicaid eligibility assessment generated by Lovable AI.
export const analyzeEligibility = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { supabase, userId } = context;
    const key = process.env.LOVABLE_API_KEY;
    if (!key) throw new Error("AI service is not configured.");

    const { data: docs, error: listErr } = await supabase
      .from("documents")
      .select("id, name, storage_path, mime_type, size_bytes")
      .eq("user_id", userId)
      .order("created_at", { ascending: true })
      .limit(25);
    if (listErr) throw new Error(listErr.message);
    if (!docs || docs.length === 0) {
      throw new Error("Upload at least one document before running the analysis.");
    }

    const MAX_BYTES = 6 * 1024 * 1024; // per file, sent to the model
    const parts: Part[] = [
      {
        type: "text",
        text:
          "You are a Medicaid eligibility screener. Review every attached document for a Long-Term Care Medicaid application. " +
          "Return a clear, plain-language report with these sections:\n\n" +
          "1. **Eligibility verdict** — one of: ✅ Likely Eligible, ⚠️ More Information Needed, or ❌ Likely Ineligible.\n" +
          "2. **Why** — 2-4 short bullets explaining the verdict based on income, assets, identity, and citizenship signals you actually saw in the documents.\n" +
          "3. **Documents reviewed** — bullet list naming each file and what it appeared to be.\n" +
          "4. **Missing or unclear items** — concrete next steps the applicant should take.\n\n" +
          "Be cautious: this is a screening estimate, not a legal determination. End with one sentence reminding the user that their specialist will confirm the final decision.",
      },
    ];

    const reviewed: { name: string; status: string }[] = [];

    for (const d of docs) {
      if ((d.size_bytes ?? 0) > MAX_BYTES) {
        reviewed.push({ name: d.name, status: "skipped (too large)" });
        continue;
      }
      const { data: blob, error: dlErr } = await supabase.storage
        .from("documents")
        .download(d.storage_path);
      if (dlErr || !blob) {
        reviewed.push({ name: d.name, status: "skipped (download failed)" });
        continue;
      }
      const bytes = new Uint8Array(await blob.arrayBuffer());
      const b64 = Buffer.from(bytes).toString("base64");
      const mime = (d.mime_type ?? "").toLowerCase();
      const lower = d.name.toLowerCase();

      if (mime.startsWith("image/") || /\.(png|jpe?g|webp|gif)$/i.test(lower)) {
        const ct = mime.startsWith("image/") ? mime : "image/jpeg";
        parts.push({ type: "image_url", image_url: { url: `data:${ct};base64,${b64}` } });
        reviewed.push({ name: d.name, status: "sent (image)" });
      } else if (mime.includes("pdf") || lower.endsWith(".pdf")) {
        parts.push({
          type: "file",
          file: { filename: d.name, file_data: `data:application/pdf;base64,${b64}` },
        });
        reviewed.push({ name: d.name, status: "sent (pdf)" });
      } else {
        reviewed.push({ name: d.name, status: "skipped (unsupported type)" });
      }
    }

    const body = {
      model: "google/gemini-2.5-flash",
      messages: [
        {
          role: "system",
          content:
            "You are a careful Medicaid eligibility screener. Only use information visible in the attached documents. Never invent numbers.",
        },
        { role: "user", content: parts },
      ],
    };

    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Lovable-API-Key": key,
      },
      body: JSON.stringify(body),
    });

    if (!res.ok) {
      const errText = await res.text().catch(() => "");
      if (res.status === 429) throw new Error("The AI is busy. Please try again in a moment.");
      if (res.status === 402) throw new Error("AI credits are exhausted. Please contact the site administrator.");
      throw new Error(`Eligibility analysis failed (${res.status}). ${errText.slice(0, 200)}`);
    }

    const json = (await res.json()) as {
      choices?: { message?: { content?: string } }[];
    };
    const reply = json.choices?.[0]?.message?.content?.trim() ?? "";
    if (!reply) throw new Error("The AI returned an empty response. Please try again.");

    let verdict: "eligible" | "needs_info" | "ineligible" = "needs_info";
    const low = reply.toLowerCase();
    if (low.includes("likely eligible") || low.includes("✅")) verdict = "eligible";
    else if (low.includes("likely ineligible") || low.includes("❌")) verdict = "ineligible";

    await supabase.from("check_ins").insert({
      user_id: userId,
      title: "AI eligibility screening completed",
      body: reply.slice(0, 1000),
      status: verdict === "eligible" ? "success" : verdict === "ineligible" ? "warning" : "info",
    });

    return { report: reply, verdict, reviewed, totalDocs: docs.length };
  });