/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedOnboardRouteImport } from './routes/_authenticated/onboard'
import { Route as AuthenticatedCrmRouteRouteImport } from './routes/_authenticated/crm/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as AuthenticatedCrmTeamRouteImport } from './routes/_authenticated/crm/team'
import { Route as AuthenticatedCrmSettingsRouteImport } from './routes/_authenticated/crm/settings'
import { Route as AuthenticatedCrmReportsRouteImport } from './routes/_authenticated/crm/reports'
import { Route as AuthenticatedCrmReferralPartnersRouteImport } from './routes/_authenticated/crm/referral-partners'
import { Route as AuthenticatedCrmPipelineRouteImport } from './routes/_authenticated/crm/pipeline'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm/leads'
import { Route as AuthenticatedCrmIntakeDashboardRouteImport } from './routes/_authenticated/crm/intake-dashboard'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin/pipeline'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedCrmLeadsNewRouteImport } from './routes/_authenticated/crm/leads.new'
import { Route as AuthenticatedCrmLeadsIdRouteImport } from './routes/_authenticated/crm/leads.$id'
import { Route as AuthenticatedCrmCasesNewRouteImport } from './routes/_authenticated/crm/cases.new'
import { Route as AuthenticatedCrmCasesIdRouteImport } from './routes/_authenticated/crm/cases.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardRoute = AuthenticatedOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRouteRoute = AuthenticatedCrmRouteRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmTeamRoute = AuthenticatedCrmTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedCrmSettingsRoute =
  AuthenticatedCrmSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmReportsRoute = AuthenticatedCrmReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedCrmReferralPartnersRoute =
  AuthenticatedCrmReferralPartnersRouteImport.update({
    id: '/referral-partners',
    path: '/referral-partners',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmPipelineRoute =
  AuthenticatedCrmPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedCrmIntakeDashboardRoute =
  AuthenticatedCrmIntakeDashboardRouteImport.update({
    id: '/intake-dashboard',
    path: '/intake-dashboard',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedCrmLeadsNewRoute =
  AuthenticatedCrmLeadsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCrmLeadsRoute,
  } as any)
const AuthenticatedCrmLeadsIdRoute = AuthenticatedCrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrmLeadsRoute,
} as any)
const AuthenticatedCrmCasesNewRoute =
  AuthenticatedCrmCasesNewRouteImport.update({
    id: '/cases/new',
    path: '/cases/new',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmCasesIdRoute = AuthenticatedCrmCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/crm': typeof AuthenticatedCrmRouteRouteWithChildren
  '/onboard': typeof AuthenticatedOnboardRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/intake-dashboard': typeof AuthenticatedCrmIntakeDashboardRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRouteWithChildren
  '/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/crm/referral-partners': typeof AuthenticatedCrmReferralPartnersRoute
  '/crm/reports': typeof AuthenticatedCrmReportsRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/team': typeof AuthenticatedCrmTeamRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/crm/cases/$id': typeof AuthenticatedCrmCasesIdRoute
  '/crm/cases/new': typeof AuthenticatedCrmCasesNewRoute
  '/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/crm/leads/new': typeof AuthenticatedCrmLeadsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/onboard': typeof AuthenticatedOnboardRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/intake-dashboard': typeof AuthenticatedCrmIntakeDashboardRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRouteWithChildren
  '/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/crm/referral-partners': typeof AuthenticatedCrmReferralPartnersRoute
  '/crm/reports': typeof AuthenticatedCrmReportsRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/team': typeof AuthenticatedCrmTeamRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/crm/cases/$id': typeof AuthenticatedCrmCasesIdRoute
  '/crm/cases/new': typeof AuthenticatedCrmCasesNewRoute
  '/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/crm/leads/new': typeof AuthenticatedCrmLeadsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRouteRouteWithChildren
  '/_authenticated/onboard': typeof AuthenticatedOnboardRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/crm/intake-dashboard': typeof AuthenticatedCrmIntakeDashboardRoute
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRouteWithChildren
  '/_authenticated/crm/pipeline': typeof AuthenticatedCrmPipelineRoute
  '/_authenticated/crm/referral-partners': typeof AuthenticatedCrmReferralPartnersRoute
  '/_authenticated/crm/reports': typeof AuthenticatedCrmReportsRoute
  '/_authenticated/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/_authenticated/crm/team': typeof AuthenticatedCrmTeamRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/crm/cases/$id': typeof AuthenticatedCrmCasesIdRoute
  '/_authenticated/crm/cases/new': typeof AuthenticatedCrmCasesNewRoute
  '/_authenticated/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/_authenticated/crm/leads/new': typeof AuthenticatedCrmLeadsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/crm'
    | '/onboard'
    | '/portal'
    | '/referrals'
    | '/admin/audit'
    | '/admin/documents'
    | '/admin/pipeline'
    | '/admin/users'
    | '/crm/intake-dashboard'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/crm/referral-partners'
    | '/crm/reports'
    | '/crm/settings'
    | '/crm/team'
    | '/api/public/leads'
    | '/admin/'
    | '/crm/'
    | '/crm/cases/$id'
    | '/crm/cases/new'
    | '/crm/leads/$id'
    | '/crm/leads/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/onboard'
    | '/portal'
    | '/referrals'
    | '/admin/audit'
    | '/admin/documents'
    | '/admin/pipeline'
    | '/admin/users'
    | '/crm/intake-dashboard'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/crm/referral-partners'
    | '/crm/reports'
    | '/crm/settings'
    | '/crm/team'
    | '/api/public/leads'
    | '/admin'
    | '/crm'
    | '/crm/cases/$id'
    | '/crm/cases/new'
    | '/crm/leads/$id'
    | '/crm/leads/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/crm'
    | '/_authenticated/onboard'
    | '/_authenticated/portal'
    | '/_authenticated/referrals'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/admin/users'
    | '/_authenticated/crm/intake-dashboard'
    | '/_authenticated/crm/leads'
    | '/_authenticated/crm/pipeline'
    | '/_authenticated/crm/referral-partners'
    | '/_authenticated/crm/reports'
    | '/_authenticated/crm/settings'
    | '/_authenticated/crm/team'
    | '/api/public/leads'
    | '/_authenticated/admin/'
    | '/_authenticated/crm/'
    | '/_authenticated/crm/cases/$id'
    | '/_authenticated/crm/cases/new'
    | '/_authenticated/crm/leads/$id'
    | '/_authenticated/crm/leads/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboard': {
      id: '/_authenticated/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof AuthenticatedOnboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm/team': {
      id: '/_authenticated/crm/team'
      path: '/team'
      fullPath: '/crm/team'
      preLoaderRoute: typeof AuthenticatedCrmTeamRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/settings': {
      id: '/_authenticated/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof AuthenticatedCrmSettingsRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/reports': {
      id: '/_authenticated/crm/reports'
      path: '/reports'
      fullPath: '/crm/reports'
      preLoaderRoute: typeof AuthenticatedCrmReportsRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/referral-partners': {
      id: '/_authenticated/crm/referral-partners'
      path: '/referral-partners'
      fullPath: '/crm/referral-partners'
      preLoaderRoute: typeof AuthenticatedCrmReferralPartnersRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/pipeline': {
      id: '/_authenticated/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof AuthenticatedCrmPipelineRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/intake-dashboard': {
      id: '/_authenticated/crm/intake-dashboard'
      path: '/intake-dashboard'
      fullPath: '/crm/intake-dashboard'
      preLoaderRoute: typeof AuthenticatedCrmIntakeDashboardRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/crm/leads/new': {
      id: '/_authenticated/crm/leads/new'
      path: '/new'
      fullPath: '/crm/leads/new'
      preLoaderRoute: typeof AuthenticatedCrmLeadsNewRouteImport
      parentRoute: typeof AuthenticatedCrmLeadsRoute
    }
    '/_authenticated/crm/leads/$id': {
      id: '/_authenticated/crm/leads/$id'
      path: '/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIdRouteImport
      parentRoute: typeof AuthenticatedCrmLeadsRoute
    }
    '/_authenticated/crm/cases/new': {
      id: '/_authenticated/crm/cases/new'
      path: '/cases/new'
      fullPath: '/crm/cases/new'
      preLoaderRoute: typeof AuthenticatedCrmCasesNewRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/cases/$id': {
      id: '/_authenticated/crm/cases/$id'
      path: '/cases/$id'
      fullPath: '/crm/cases/$id'
      preLoaderRoute: typeof AuthenticatedCrmCasesIdRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
    AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCrmLeadsRouteChildren {
  AuthenticatedCrmLeadsIdRoute: typeof AuthenticatedCrmLeadsIdRoute
  AuthenticatedCrmLeadsNewRoute: typeof AuthenticatedCrmLeadsNewRoute
}

const AuthenticatedCrmLeadsRouteChildren: AuthenticatedCrmLeadsRouteChildren = {
  AuthenticatedCrmLeadsIdRoute: AuthenticatedCrmLeadsIdRoute,
  AuthenticatedCrmLeadsNewRoute: AuthenticatedCrmLeadsNewRoute,
}

const AuthenticatedCrmLeadsRouteWithChildren =
  AuthenticatedCrmLeadsRoute._addFileChildren(
    AuthenticatedCrmLeadsRouteChildren,
  )

interface AuthenticatedCrmRouteRouteChildren {
  AuthenticatedCrmIntakeDashboardRoute: typeof AuthenticatedCrmIntakeDashboardRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRouteWithChildren
  AuthenticatedCrmPipelineRoute: typeof AuthenticatedCrmPipelineRoute
  AuthenticatedCrmReferralPartnersRoute: typeof AuthenticatedCrmReferralPartnersRoute
  AuthenticatedCrmReportsRoute: typeof AuthenticatedCrmReportsRoute
  AuthenticatedCrmSettingsRoute: typeof AuthenticatedCrmSettingsRoute
  AuthenticatedCrmTeamRoute: typeof AuthenticatedCrmTeamRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedCrmCasesIdRoute: typeof AuthenticatedCrmCasesIdRoute
  AuthenticatedCrmCasesNewRoute: typeof AuthenticatedCrmCasesNewRoute
}

const AuthenticatedCrmRouteRouteChildren: AuthenticatedCrmRouteRouteChildren = {
  AuthenticatedCrmIntakeDashboardRoute: AuthenticatedCrmIntakeDashboardRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRouteWithChildren,
  AuthenticatedCrmPipelineRoute: AuthenticatedCrmPipelineRoute,
  AuthenticatedCrmReferralPartnersRoute: AuthenticatedCrmReferralPartnersRoute,
  AuthenticatedCrmReportsRoute: AuthenticatedCrmReportsRoute,
  AuthenticatedCrmSettingsRoute: AuthenticatedCrmSettingsRoute,
  AuthenticatedCrmTeamRoute: AuthenticatedCrmTeamRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedCrmCasesIdRoute: AuthenticatedCrmCasesIdRoute,
  AuthenticatedCrmCasesNewRoute: AuthenticatedCrmCasesNewRoute,
}

const AuthenticatedCrmRouteRouteWithChildren =
  AuthenticatedCrmRouteRoute._addFileChildren(
    AuthenticatedCrmRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCrmRouteRoute: typeof AuthenticatedCrmRouteRouteWithChildren
  AuthenticatedOnboardRoute: typeof AuthenticatedOnboardRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCrmRouteRoute: AuthenticatedCrmRouteRouteWithChildren,
  AuthenticatedOnboardRoute: AuthenticatedOnboardRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
